library(shiny)
library(shinyjs)
library(DT)
library(MASS)
library(summarytools)
library(mlbench)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(caret)
library(nnet)
library(e1071)
library(DMwR)
library(PerformanceAnalytics)
library(scales)
library(alluvial)
library(recipes)
library(dbscan)
library(plotly)
#library(rPython)
library(shinythemes)
library(shinydashboard)
library(shinyWidgets)
#library(leaflet)
#library(maps)
#library(geojsonio)


